//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    
    public enum AttributeType : int
    {
        String = 0,
        Number = 1,
        Date = 2,
        Person = 3,
        Location = 4,
        Path = 5,
        TimeStamp = 6
    }
}
