//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos {
  using System;
  using System.Collections.Generic;
  using System.Runtime.Serialization;

  [DataContract(IsReference = true)]
  public partial class AttributeValue {
    [DataMember] public int Id { get; set; }
    [DataMember] public int AttributeId { get; set; }
    [DataMember] public string Value { get; set; }
    [DataMember] public int MediaId { get; set; }

    [DataMember] public virtual Media Media { get; set; }
    [DataMember] public virtual Attribute Attribute { get; set; }
  }
}
